name: pppoev6

services:
  pppoev6:
    image: scenario_env_ipv6
    build: .
    network_mode: "host"
    volumes:
      - ./conf/pppd_option.conf:/etc/ppp/pppoe-server-options
      - ./conf/pap-secrets:/etc/ppp/pap-secrets
      - ./conf/radvd.conf:/etc/radvd.m4
      - ./conf/dhcpd6.conf:/etc/dhcp/dhcpd6.conf
      - ./scripts/ip-up:/etc/ppp/ip-up.d/0001pppoev6
      - ./env_data/:/var/env_data
    # Note: 需要权限用于生成 /dev/ppp
    privileged: true
    # Note: 给接口配置地址需要网络管理能力
    cap_add:
      - NET_ADMIN
    # -F 前台运行
    # -N 最大并行session数量
    # -I 指定接口
    # -L 服务器 pppoe 接口 ip
    # -R pppoe 地址池的起始 ip
    command: pppoe-server -F -I ${IFACE} -L ${LOCAL_IP} -R ${POOL_START_IP} -N 20

