name: dhcpv6-pd

# 如 Ubuntu 发行版, 由于 NetworkManager 使用了 netlink 监听的接口事件, 当接口 down 的时候将其配置写到 sysctl 中, 相同值时会覆盖前面脚本的修改. 
# 故需要先将 NetworkManager 中的接口 ipv6 功能开启

services:
  radvd:
    image: scenario_envs/ipv6
    build: .
    network_mode: "host"
    environment:
      - IFACE=${IFACE}
    volumes:
      - ./conf/radvd.conf:/etc/radvd.m4
    # Note: 需要权限用于生成 /dev/ppp
    privileged: true
    # Note: 给接口配置地址需要网络管理能力
    cap_add:
      - NET_ADMIN
    # -C 指定配置文件
    command: >
      sh -c "
        sysctl -w net.ipv6.conf.$${IFACE}.disable_ipv6=0 &&
        sysctl -w net.ipv6.conf.$${IFACE}.forwarding=1 &&
        ip link set dev $${IFACE} up &&
        m4 -D__IFACE__=$${IFACE} /etc/radvd.m4 > /etc/radvd-$${IFACE}.conf &&
        radvd -n -C /etc/radvd-$${IFACE}.conf
      "

  dhcpd6:
    image: scenario_envs/ipv6
    build: .
    network_mode: "host"
    environment:
      - IFACE=${IFACE}
    volumes:
      - ./conf/dhcpd6.conf:/etc/dhcp/dhcpd6.conf
      - ./env_data/:/var/env_data
    # Note: 需要权限用于生成 /dev/ppp
    privileged: true
    # Note: 给接口配置地址需要网络管理能力
    cap_add:
      - NET_ADMIN
    # -6 表示启用ipv6
    # -cf 指定配置文件
    command: >
      sh -c "
        sysctl -w net.ipv6.conf.$${IFACE}.disable_ipv6=0 &&
        sysctl -w net.ipv6.conf.$${IFACE}.forwarding=1 &&
        ip link set dev $${IFACE} up &&
        ip -6 addr flush dev $${IFACE} &&
        ip -6 addr add 2024::1/48 dev $${IFACE} &&
        mkdir -p /var/env_data &&
        touch /var/env_data/dhcpd6.leases &&
        dhcpd -6 -cf /etc/dhcp/dhcpd6.conf $${IFACE}
      "
