name: ipv6_server

services:
  radvd:
    image: dreamhost/radvd
    pull_policy: missing
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./conf/radvd.conf:/etc/radvd.conf:ro
    command: "-d 2 -m stderr"

  dhcpdv6:
    image: networkboot/dhcpd
    pull_policy: missing
    network_mode: "host"
    environment:
      - DHCPD_PROTOCOL=6
    volumes:
      - ./data:/data
      - ./conf/dhcpd6.conf:/conf/dhcpd.conf
    # command: 'enp6s0f4u2u1c2'
    command: 'eth4'

